<a href="https://colab.research.google.com/github/nadiahsahidah/classification-with-fasttext/blob/main/Copy_of_(prototype)_fasttext_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install fasttext

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.8/68.8 kB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Using cached pybind11-2.11.1-py3-none-any.whl (227 kB)
  Created wheel for fasttext: filename=fasttext-0.9.2-cp310-cp310-linux_x86_64.whl size=4199770 sha256=054c3507a9ea5d5d2f0c7ab7db7b27c12468cbc425faf3e8295f549548b7720e
  Stored in directory: /root/.cache/pip/wheels/a5/13/75/f811c84a8ab36eedbaef977a6a58a98990e8e0f1967f98f394
Successfully built fasttext


In [ ]:
from google.colab import drive
import random
import numpy as np
from sklearn.model_selection import train_test_split
import fasttext

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!ls '/content/drive/MyDrive/fasttext_dataset'

dataset_1000.txt


# Persiapan

In [ ]:
def initialization():
  # Parameter
  SEED = 27
  PATH = '/content/drive/MyDrive/fasttext_dataset/dataset_1000.txt'

  # Read file dataset
  with open(PATH, 'r') as f:
    dataset = f.readlines()

  # Save dataset into list
  dataset = [dt.strip() for dt in dataset]

  # Shuffle dataset
  random.seed(SEED)
  random.shuffle(dataset)

  # Split label and content
  labels = []
  contents = []
  for dt in dataset:
    parts = dt.split(' ', 1)
    label = parts[0]
    content = parts[1]
    labels.append(label)
    contents.append(content)

  return labels, contents

# Praproses

In [ ]:
def preprocessing(data):
  data = convert_lower_case(data)
  data = remove_punctuation(data)
  data = remove_single_character(data)
  data = remove_stopwords(data)
  # stemming
  data = praproses_stem(data)
  # lemmatization
  data = lemmatization(data)
  return data

In [ ]:
def remove_single_character(data):
  cleaned_data = []
  for dt in data:
    words = dt.split()
    new_data = ""
    for word in words:
      if len(word) > 1:
        new_data = new_data + " " + word
    cleaned_data.append(new_data)
  return cleaned_data

In [ ]:
def convert_lower_case(data):
  return np.char.lower(data)

In [ ]:
def remove_punctuation(data):
  SYMBOLS = ",!\"\'#$%&()*+-./:;<=>?@[\]^_`{|}~\n"
  for s in SYMBOLS:
    data = np.char.replace(data, s, '')
  return data

In [ ]:
def remove_stopwords(data):
  STOPWORDS = [
      'saya', 'ga', 'di', 'mas', 'ya',
      'aja', 'nya', 'ini', 'aku', 'ke',
      'lu', 'ada', 'pak', 'gw', 'mbak',
      'kak', 'gue', 'nih', 'yang', 'dan',
      'tapi', 'yg', 'deh', 'gua', 'kk',
      'apa', 'kamu', 'lo', 'dong', 'anda',
      'hehe', 'kita', 'kau', 'itu', 'woi'
      ]
  cleaned_data = []
  for dt in data:
    words = dt.split()
    new_data = ""
    for word in words:
      if word not in STOPWORDS:
        new_data = new_data + " " + word
    cleaned_data.append(new_data)
  return cleaned_data

In [ ]:
!pip install Sastrawi
import nltk
nltk.download('punkt')
nltk.download('wordnet')
from nltk.stem import PorterStemmer
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

def praproses_stem(data):
    cleaned_data = []
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()

    for dt in data:
        stemmed_words = [stemmer.stem(word) for word in nltk.word_tokenize(dt)]
        stemmed_data = ' '.join(stemmed_words)
        cleaned_data.append(stemmed_data)
    return cleaned_data

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 2.5 MB/s eta 0:00:00


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


In [ ]:
def lemmatization(data):
    cleaned_data = []
    for dt in data:
        lemmatizer = nltk.WordNetLemmatizer()
        cleaned_data.append(' '.join([lemmatizer.lemmatize(word) for word in nltk.word_tokenize(dt)]))
    return cleaned_data

In [ ]:
# Data yang akan diproses
data = ["boleh transfer secukupnya kak", "anjing lama kali", "apakah anda butuh bantuan lain?"]

# Proses preprocessing data
processed_data = preprocessing(data)

# Cetak hasil
for text in processed_data:
    print(text)

boleh transfer cukup
anjing lama kali
apakah butuh bantu lain


In [ ]:
#from collections import Counter
#def count_word_occurence(data):
#   text = " ".join(data)
#  words = text.split()
#  word_counts = Counter(words)
#  sorted_word_counts = word_counts.most_common()
#  for word, count in sorted_word_counts:
#    print(f"{word} : {count}")

In [ ]:
def splitting(labels, contents):
  # merge label and content
  cleaned_dataset = []
  for i in range(len(contents)):
    data = labels[i] + " " + contents[i]
    cleaned_dataset.append(data)

  # split dataset (train: 80%, valid: 20%)
  data_train, data_valid = train_test_split(cleaned_dataset, test_size=0.2, random_state=27)
  return data_train, data_valid

In [ ]:
def get_cleaned_data():
  labels, contents = initialization()
  contents = preprocessing(contents)
  data_train, data_valid = splitting(labels, contents)
  return data_train, data_valid

In [ ]:
data_train, data_valid = get_cleaned_data()

In [ ]:
print(f"train data: {len(data_train)}")
print(f"valid data: {len(data_valid)}")

train data: 800
valid data: 200


In [ ]:
TRAINPATH = '/content/data.train'
VALIDPATH = '/content/data.valid'

In [ ]:
with open(TRAINPATH, 'w') as f:
  for data in data_train:
    f.write(data + '\n')

In [ ]:
with open(VALIDPATH, 'w') as f:
  for data in data_valid:
    f.write(data + '\n')

In [ ]:
# Buat ngefilter stopwords
# count_word_occurence(contents)

# Membangun model

In [ ]:
!pwd

/content


In [ ]:
'''
Hyperparameter / parameter buat fungsi train_supervised()
- epoch => berapa kali dataset nya dipake buat ngelatih si model (umumnya semakin tinggi semakin berpotensi overfit)
- lr => learning rate => seberapa cepat model belajar (umumnya semakin tinggi semakin berpotensi overfit)
- loss => kalau value nya pake 'hs' artinya hierarchical softmax. Intinya sih buat mempercepat proses training model aja
- wordNgrams => implementasi Ngrams => bisa ngereduksi overfit
- autotuneValidationFile => buat auto tuning hyperparameter ampe dapet yang paling optimal
- autotuneDuration => durasi buat auto tuning
- bucket =>
- dim =>
'''
model = fasttext.train_supervised(input=TRAINPATH, epoch=10, lr=0.2, wordNgrams=3)

# Uji coba model

In [ ]:
model.test(TRAINPATH)

(800, 0.8825, 0.8825)

In [ ]:
model.test(VALIDPATH)

# overfit => akurasi train jauh lebih gede dibanding akurasi test
# underfit => akurasi train dan test sama2 rendah

(200, 0.72, 0.72)

In [ ]:
'''
Hyperparameter / parameter buat fungsi predict
- k => buat multi class classification. k = -1 artinya predict buat seluruh kelas yang ada
- threshold => ambang batas. Semua label dengan probabilitas < threshold ga bakal ditampilin
'''

model.predict('sedang dimana kak?', k=-1)

(('__label__none', '__label__sexual', '__label__fraud', '__label__harsh'),
 array([0.31532931, 0.28220537, 0.22963168, 0.1728736 ]))

In [ ]:
model.predict('nyampe mana?', k=-1)

(('__label__none', '__label__sexual', '__label__harsh', '__label__fraud'),
 array([0.39694005, 0.22989401, 0.21832456, 0.15488139]))

In [ ]:
model.predict('woi anjing lu di mana sih? ga nyampe2', k=-1, threshold=0.6)

(('__label__harsh',), array([0.70123601]))

In [ ]:
model.predict('kontol banget lu dah', k=-1)

(('__label__harsh', '__label__none', '__label__sexual', '__label__fraud'),
 array([0.31783286, 0.2931008 , 0.27692321, 0.11218314]))

In [ ]:
model.predict('kamu sexy banget deh hehe', k=-1)

(('__label__sexual', '__label__none', '__label__fraud', '__label__harsh'),
 array([0.39946377, 0.23441844, 0.20278849, 0.16336928]))

# Menyimpan model

In [ ]:
MODELPATH = '/content/model_chat.bin'
model.save_model(MODELPATH)

In [ ]:
# Memeriksa ukuran model
!ls -lh $MODELPATH

-rw-r--r-- 1 root root 764M Oct 16 09:58 /content/model_chat.bin


# Model dengan auto-tuning hyperparameter (perlu RAM yang lebih banyak)

In [ ]:
# Sejauh ini durasi nya cuma bisa 1 menit
model = fasttext.train_supervised(input=TRAINPATH, autotuneValidationFile=VALIDPATH, autotuneDuration=60)

In [ ]:
model.test(TRAINPATH)

(800, 0.99875, 0.99875)

In [ ]:
model.test(VALIDPATH)

(200, 0.915, 0.915)

In [ ]:
model.predict('nyampe mana?', k=-1)

(('__label__none', '__label__harsh', '__label__sexual', '__label__fraud'),
 array([0.52381396, 0.24753724, 0.22505352, 0.00363527]))

In [ ]:
model.predict('woi anjing lu di mana sih? ga nyampe2', k=-1, threshold=0.6)

(('__label__harsh',), array([0.98275894]))

In [ ]:
model.predict('kontol banget lu dah', k=-1)

(('__label__harsh', '__label__sexual', '__label__none', '__label__fraud'),
 array([8.84318590e-01, 1.13209367e-01, 2.27600336e-03, 2.35964195e-04]))

In [ ]:
model.predict('kamu sexy banget deh hehe', k=-1)

(('__label__sexual', '__label__harsh', '__label__none', '__label__fraud'),
 array([0.95761478, 0.02583398, 0.01108626, 0.00550495]))

In [ ]:
# Perlu dataset lebih gede lagi biar probability nya ningkat
model.predict('pagi mas', k=-1)

(('__label__none', '__label__sexual', '__label__harsh', '__label__fraud'),
 array([9.71013188e-01, 2.76272669e-02, 1.37101149e-03, 2.85055667e-05]))

In [ ]:
model.predict('selamat siang ka', k=-1)

(('__label__none', '__label__harsh', '__label__sexual', '__label__fraud'),
 array([9.84597802e-01, 1.46884182e-02, 3.83288512e-04, 3.70558293e-04]))

In [ ]:
model.predict('terima kasih kak ')